import { useRef } from "react";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useRouter } from "next/router";
import ParticlesBackground from "@/components/ParticlesBackground";
import Heart from "@/components/Heart";

export default function Home() {
  const router = useRouter();
  const { n = "", m = "" } = router.query;
  const name = Buffer.from(n.toString(), "base64").toString("ascii");
  const message = Buffer.from(m.toString(), "base64").toString("ascii");

  const musicPlayers = useRef<HTMLAudioElement | undefined>(
    typeof Audio !== "undefined" ? new Audio("/tada-fanfare.mp3") : undefined
  );

  return (
    <div
      className="container"
      onClick={() => {
        if (m || n) {
          musicPlayers.current?.play();
        }
      }}
    >
      <Head>
        <title>Octavio Appreciates You</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {(m || n) && <ParticlesBackground></ParticlesBackground>}
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            {(n || m) && (m !== "" || n !== "")
              ? `Octavio created this website to say`
              : "Octavio has nothing to say to you at this moment"}
          </p>
        </div>
        <div className={styles.main}>
          <p>
            {(n || m) && (m !== "" || n !== "")
              ? `${name}${m === "" || n === "" ? "" : ", "} ${message}`
              : ""}
          </p>
          {(n || m) && <Heart />}
        </div>
      </main>
    </div>
  );
}
